baseURL: "/"
languageCode: "en-us"
title: "phylsix fun"
theme: "xmin"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Categories
      url: "categories/"
      weight: 3
    - name: Tags
      url: "tags/"
      weight: 4
    - name: Subscribe
      url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  GitHubEdit: "https://github.com/phylsix/www/edit/master/content/"
  footer: "&copy; [Weinan SI](https://phylsix.netlify.app/) 2021 | [github](https://github.com/phylsix) | [theme](https://themes.gohugo.io/hugo-xmin/) | [markdown](./post/2016/02/14/a-plain-markdown-post/)"

markup:
  goldmark:
    renderer:
      unsafe: true